[
  {
    "id": 1,
    "fornecedor": "Techenerg",
    "disciplina": "TGM",
    "atividade": "Revisão / Inspeção",
    "valor": 86892,
    "data_inicio": "2026-08-25",
    "data_fim": "2026-09-05",
    "responsavel": "Claudio Andrade",
    "contato": "(19) 99214-1524",
    "escopo": "Escopo referente ao TG1: verificação da parametrização do regulador de velocidade 505 XT; stroke de válvulas via CPC2 (HP/LP); instalação de sensores de vibração e deslocamento axial do TG; revisão do painel de controle da turbina, painel de Proteção/Excitação do Gerador e painel de Import/Export; verificação da parametrização dos DSLC2 XT e MSLC2 XT; supervisão da correção das lógicas de controle no PLC (MSLC2/DSLC2 XT — requer técnico de Automação da RRP ou contratação do parceiro Softenge); testes de sobrevelocidade, sincronismo, carga e rejeição de carga; emissão de relatório técnico.",
    "status": "PENDENTE",
    "observacao": ""
  },
  {
    "id": 2,
    "fornecedor": "TGM",
    "disciplina": "TGM",
    "atividade": "Revisão Geral",
    "valor": 800000,
    "data_inicio": "2026-08-20",
    "data_fim": "2026-09-05",
    "responsavel": "",
    "contato": "",
    "escopo": "Revisão geral, jateamento com CO₂ (gelo seco) do rotor e porta-palhetas, ensaios de líquido penetrante, comissionamento a frio/quente e start-up.",
    "status": "PENDENTE",
    "observacao": "Responsável e contato não informados na proposta — pendente de complemento."
  },
  {
    "id": 3,
    "fornecedor": "NDR Calibração e Manutenção",
    "disciplina": "INSTRUMENTACAO",
    "atividade": "Calibração",
    "valor": 45572,
    "data_inicio": "2026-08-25",
    "data_fim": "2026-08-27",
    "responsavel": "Vitor Silva",
    "contato": "(11) 99970-5220",
    "escopo": "Calibração RBC in loco de 25 totalizadores de vazão + 6 transmissores diferenciais de pressão.",
    "status": "PENDENTE",
    "observacao": ""
  },
  {
    "id": 4,
    "fornecedor": "Eletrolucas",
    "disciplina": "ELETRICA",
    "atividade": "Inspeção / Manutenção Preventiva",
    "valor": 73582,
    "data_inicio": "2026-08-25",
    "data_fim": "2026-09-05",
    "responsavel": "Guilherme",
    "contato": "(11) 91130-1403",
    "escopo": "Manutenção preventiva em 13 disjuntores de Média Tensão a vácuo (ABB tipo VD4/P 17.12.32 e 17.20.32 — Classe 15 kV) e sub-cubículos.",
    "status": "PENDENTE",
    "observacao": ""
  },
  {
    "id": 5,
    "fornecedor": "Casa do Construtor",
    "disciplina": "CIVIL",
    "atividade": "Locação de Andaime",
    "valor": 604,
    "data_inicio": "2026-08-24",
    "data_fim": "2026-08-28",
    "responsavel": "Samuel",
    "contato": "(66) 9965-0672",
    "escopo": "Fornecimento de andaime para montagem de acesso aos transmissores de vazão, viabilizando a retirada para calibração.",
    "status": "PENDENTE",
    "observacao": ""
  },
  {
    "id": 6,
    "fornecedor": "CDMAD / Gesso Acartonado",
    "disciplina": "CIVIL",
    "atividade": "Infraestrutura",
    "valor": 27405,
    "data_inicio": "2026-08-24",
    "data_fim": "2026-08-28",
    "responsavel": "Maycon",
    "contato": "(66) 9663-4914",
    "escopo": "Tamponamento com gesso acartonado das aberturas dos CCMs: Moinho, Destilaria, Fermentação, Secagem, ETE, Caldeira, Dujua e Auxiliar Gerador.",
    "status": "PENDENTE",
    "observacao": ""
  }
]
